more about the data: http://insideairbnb.com/copenhagen/

In [46]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [26]:
df = pd.read_csv('data/listings_CPH.csv')

In [27]:
df.T

0      \
id                                              6983   
name                            Copenhagen 'N Livin'   
host_id                                        16774   
host_name                                      Simon   
neighbourhood_group                              NaN   
neighbourhood                                Nrrebro   
latitude                                    55.68641   
longitude                                   12.54741   
room_type                            Entire home/apt   
price                                            898   
minimum_nights                                     3   
number_of_reviews                                172   
last_review                               2022-06-21   
reviews_per_month                               1.08   
calculated_host_listings_count                     1   
availability_365                                   0   
number_of_reviews_ltm                              4   
license                                          NaN   

                                                              1      \
id                                                            26057   
name                            Lovely house - most attractive area   
host_id                                                      109777   
host_name                                                      Kari   
neighbourhood_group                                             NaN   
neighbourhood                                              Indre By   
latitude                                                   55.69307   
longitude                                                  12.57649   
room_type                                           Entire home/apt   
price                                                          2600   
minimum_nights                                                    4   
number_of_reviews                                                59   
last_review                                              2022-08-09   
reviews_per_month                                              0.55   
calculated_host_listings_count                                    1   
availability_365                                                303   
number_of_reviews_ltm                                             8   
license                                                         NaN   

                                                                    2      \
id                                                                  26473   
name                            City Centre Townhouse Sleeps 1-10 persons   
host_id                                                            112210   
host_name                                                           Julia   
neighbourhood_group                                                   NaN   
neighbourhood                                                    Indre By   
latitude                                                         55.67602   
longitude                                                         12.5754   
room_type                                                 Entire home/apt   
price                                                                3250   
minimum_nights                                                          3   
number_of_reviews                                                     300   
last_review                                                    2022-09-10   
reviews_per_month                                                    2.06   
calculated_host_listings_count                                          3   
availability_365                                                       56   
number_of_reviews_ltm                                                   7   
license                                                               NaN   

                                                          3      \
id                                                        29118   
name                            Be

### Multi Class Classification
predict whether the price of a rental is either ‘low’, ‘med’ or ‘high’. We again leave it up to you to decide how you want to define ‘low’, ‘med’ and ‘high’. For example, ‘low’ could mean that the price of the rental is lower than the 33th percentile of prices in the city, ‘medium’ is a price between the 33th and 66th percentile, and ‘high’ is a price higher than the 66th percentile. You may also use any other threshold to define the classes low,
medium and high. Here, there is no benchmark, try to build the best possible classifier you can (considering all the metrics we looked at f1 score, confusion matrix, etc.).

Lets use the method suggested where
- price < 33 percentile is classified as low
- 33 percentile <= price <= 66 percentile is classified as med
- price > 66 percentile is classified as high

In [28]:
#calculate the 33 and 66 percentile of prices
quantile_66 = df['price'].quantile(0.66)
quantile_33 = df['price'].quantile(0.33)

# preparing the targer variable (price)
df['price_class']=(df['price'].apply(lambda x: 'high' if x > quantile_66 else ('medium' if x > quantile_33 else 'low'))).astype(str)

In [29]:
# preparing the data
# decide which columns to feature in the classifier
featured_columns = ['neighbourhood', 'room_type', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'availability_365', 'calculated_host_listings_count']

#get dummy variables
features = pd.get_dummies(df[featured_columns], columns=['neighbourhood', 'room_type']).fillna(0)

#standardize remaining data
std_columns = ['minimum_nights', 'number_of_reviews', 'reviews_per_month', 'availability_365', 'calculated_host_listings_count']
std_features = features.copy()
std_features[std_columns] = (std_features[std_columns] - std_features[std_columns].mean()) / std_features[std_columns].std()

In [30]:
#splitting data into training and testing sets (80 - 20 split)

x_train, x_test, y_train, y_test = model_selection.train_test_split(features, df['price_class'], test_size= 0.2, random_state = 1)

This is a multiclass classification problem, so binary classifiers like logistic regression and support vector machines will not directly work.

However, we can split the multiclass problem into multiple binary classification problems which then could be plugged into a logistic regression or SVM model.

First, lets look at logistic regression. Here, we can use a method called One-vs-Rest (OVR).
- we split the problem into 3 different binary classification datasets:
    - High vs [Medium, Low]
    - Medium vs [High, Low]
    - Low vs [High, Medium]

This can be easily implemented with LogisticRegression by setting the multi_class input to 'ovr'

In [31]:
lr = LogisticRegression(multi_class='ovr', solver='liblinear')
lr.fit(x_train, y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [33]:
#lets check the accuracy
y_pred_lr = lr.predict(x_test)

print("accuracy score: %f" % accuracy_score(y_test, y_pred_lr))
print("F1-score: %f" % f1_score(y_test, y_pred_lr, average='micro'))
print("confusion matrix:")
print(confusion_matrix(y_test, y_pred_lr))

accuracy score: 0.498371
F1-score: 0.498371
confusion matrix:
[[415 103 317]
 [ 92 460 403]
 [283 188 502]]


In [40]:
svc = SVC(decision_function_shape='ovo')

In [41]:
svc.fit(x_train, y_train)

SVC(decision_function_shape='ovo')

In [44]:
#lets check the accuracy
y_pred_svc = svc.predict(x_test)

print("accuracy score: %f" % accuracy_score(y_test, y_pred_svc))
print("F1-score: %f" % f1_score(y_test, y_pred_svc, average='micro'))
print("confusion matrix:")
print(confusion_matrix(y_test, y_pred_svc))

accuracy score: 0.412233
F1-score: 0.412233
confusion matrix:
[[378 345 112]
 [222 616 117]
 [293 535 145]]


In [51]:
dt=DecisionTreeClassifier()

In [52]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [53]:
#lets check the accuracy
y_pred_dt = dt.predict(x_test)

print("accuracy score: %f" % accuracy_score(y_test, y_pred_dt))
print("F1-score: %f" % f1_score(y_test, y_pred_dt, average='micro'))
print("confusion matrix:")
print(confusion_matrix(y_test, y_pred_dt))

accuracy score: 0.452045
F1-score: 0.452045
confusion matrix:
[[386 152 297]
 [196 489 270]
 [308 291 374]]
